---
- name:  Delete {{ az_vm_name }} VM from {{ az_resourcegroup_name }} on {{ az_region }}
  local_action:
    moduleazure_rm_virtualmachine: {{ az_vm_name }}
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    availability_set: "{{ az_availabilitysets_name }}"
    state: absent

- name:  Delete {{ az_vm_nic_name }} Nic from {{ az_resourcegroup_name }} on {{ az_region }}
  local_action:
    module: azure_rm_networkinterface
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    name: "{{ az_vm_nic_name }}"
    state: absent

- name:  Delete {{ azure_rm_publicipaddress }} Public IP from {{ az_resourcegroup_name }} on {{ az_region }}
  local_action:
    module: azure_rm_networkinterface
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    name: "{{ azure_rm_publicipaddress }}"
    state: absent

- name: Delete {{ az_vm_disk_name }} Disk from {{ az_resourcegroup_name }} on {{ az_region }}
  local_action:
    module: azure_rm_managed_disk
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    name: "{{ az_vm_disk_name }}"
    state: absent
